// <auto-generated />
using System;
using ArcheryWebsite.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArcheryWebsite.Migrations
{
    [DbContext(typeof(ArcheryDbContext))]
    [Migration("20251121131321_AddSystemLogs")]
    partial class AddSystemLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ArcheryWebsite.Models.Archer", b =>
                {
                    b.Property<int>("ArcherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("archer_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArcherId"));

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<int>("DefaultEquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("default_equipment_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("enum('Male','Female','Other')")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ArcherId")
                        .HasName("PRIMARY");

                    b.ToTable("archer", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Arrow", b =>
                {
                    b.Property<int>("ArrowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("arrow_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ArrowId"));

                    b.Property<int>("ArrowValue")
                        .HasColumnType("int")
                        .HasColumnName("arrow_value");

                    b.Property<int>("EndId")
                        .HasColumnType("int")
                        .HasColumnName("end_id");

                    b.Property<ulong>("IsX")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(0ul)
                        .HasColumnName("is_x");

                    b.HasKey("ArrowId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "EndId" }, "end_id");

                    b.ToTable("arrow", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Competition", b =>
                {
                    b.Property<int>("CompId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comp_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CompId"));

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comp_name");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsClubChampionship")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_club_championship");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("CompId")
                        .HasName("PRIMARY");

                    b.ToTable("competition", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.End", b =>
                {
                    b.Property<int>("EndId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("end_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EndId"));

                    b.Property<int>("EndNumber")
                        .HasColumnType("int")
                        .HasColumnName("end_number");

                    b.Property<int>("EndScore")
                        .HasColumnType("int")
                        .HasColumnName("end_score");

                    b.Property<int>("RangeId")
                        .HasColumnType("int")
                        .HasColumnName("range_id");

                    b.Property<int?>("RoundRangeId")
                        .HasColumnType("int")
                        .HasColumnName("round_range_id");

                    b.Property<int>("ScoreId")
                        .HasColumnType("int")
                        .HasColumnName("score_id");

                    b.HasKey("EndId")
                        .HasName("PRIMARY");

                    b.HasIndex("RoundRangeId");

                    b.HasIndex(new[] { "RangeId" }, "range_id");

                    b.HasIndex(new[] { "ScoreId" }, "score_id");

                    b.ToTable("end", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("DivisionType")
                        .IsRequired()
                        .HasColumnType("enum('Recurve','Compound','Recurve Barebow','Compound Barebow','Longbow')")
                        .HasColumnName("division_type");

                    b.HasKey("EquipmentId")
                        .HasName("PRIMARY");

                    b.ToTable("equipment", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Range", b =>
                {
                    b.Property<int>("RangeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("range_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RangeId"));

                    b.Property<int>("DistanceMeters")
                        .HasColumnType("int")
                        .HasColumnName("distance_meters");

                    b.Property<int>("EndCount")
                        .HasColumnType("int")
                        .HasColumnName("end_count");

                    b.Property<int>("FaceSizeCm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(122)
                        .HasColumnName("face_size_cm");

                    b.HasKey("RangeId")
                        .HasName("PRIMARY");

                    b.ToTable("range", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.RoundEquivalence", b =>
                {
                    b.Property<int>("EquivalenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("equivalence_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EquivalenceId"));

                    b.Property<int>("EquivalentRoundId")
                        .HasColumnType("int")
                        .HasColumnName("equivalent_round_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("EquivalenceId");

                    b.HasIndex("EquivalentRoundId");

                    b.HasIndex("RoundId");

                    b.ToTable("round_equivalence", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Roundrange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RangeId")
                        .HasColumnType("int")
                        .HasColumnName("range_id");

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    b.Property<int>("SequenceNumber")
                        .HasColumnType("int")
                        .HasColumnName("sequence_number");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "RangeId" }, "range_id")
                        .HasDatabaseName("range_id1");

                    b.HasIndex(new[] { "RoundId" }, "round_id");

                    b.ToTable("roundrange", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("score_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int>("ArcherId")
                        .HasColumnType("int")
                        .HasColumnName("archer_id");

                    b.Property<int?>("CompId")
                        .HasColumnType("int")
                        .HasColumnName("comp_id");

                    b.Property<DateOnly>("DateShot")
                        .HasColumnType("date")
                        .HasColumnName("date_shot");

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    b.Property<int>("TotalScore")
                        .HasColumnType("int")
                        .HasColumnName("total_score");

                    b.HasKey("ScoreId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ArcherId" }, "archer_id");

                    b.HasIndex(new[] { "CompId" }, "comp_id");

                    b.HasIndex(new[] { "RoundId" }, "round_id")
                        .HasDatabaseName("round_id1");

                    b.ToTable("score", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Stagingscore", b =>
                {
                    b.Property<int>("StagingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("staging_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StagingId"));

                    b.Property<int>("ArcherId")
                        .HasColumnType("int")
                        .HasColumnName("archer_id");

                    b.Property<string>("ArrowValues")
                        .HasColumnType("longtext")
                        .HasColumnName("arrow_values");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("date_time");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int")
                        .HasColumnName("equipment_id");

                    b.Property<int>("RawScore")
                        .HasColumnType("int")
                        .HasColumnName("raw_score");

                    b.Property<int>("RoundId")
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("enum('pending','approved','rejected')")
                        .HasColumnName("status")
                        .HasDefaultValueSql("'pending'");

                    b.HasKey("StagingId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ArcherId" }, "archer_id")
                        .HasDatabaseName("archer_id1");

                    b.HasIndex(new[] { "EquipmentId" }, "equipment_id");

                    b.HasIndex(new[] { "RoundId" }, "round_id")
                        .HasDatabaseName("round_id2");

                    b.ToTable("stagingscore", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.SystemLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("log_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("details");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ip_address");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("level");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("timestamp");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("user");

                    b.HasKey("LogId");

                    b.ToTable("system_log", (string)null);
                });

            modelBuilder.Entity("Round", b =>
                {
                    b.Property<int>("RoundId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("round_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoundId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("RoundFamilyCode")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("round_family_code");

                    b.Property<string>("RoundName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("round_name");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date")
                        .HasColumnName("valid_from");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date")
                        .HasColumnName("valid_to");

                    b.HasKey("RoundId")
                        .HasName("PRIMARY");

                    b.ToTable("round", (string)null);
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Arrow", b =>
                {
                    b.HasOne("ArcheryWebsite.Models.End", "End")
                        .WithMany("Arrows")
                        .HasForeignKey("EndId")
                        .IsRequired()
                        .HasConstraintName("arrow_ibfk_1");

                    b.Navigation("End");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.End", b =>
                {
                    b.HasOne("ArcheryWebsite.Models.Range", "Range")
                        .WithMany("Ends")
                        .HasForeignKey("RangeId")
                        .IsRequired()
                        .HasConstraintName("end_ibfk_2");

                    b.HasOne("ArcheryWebsite.Models.Roundrange", "RoundRange")
                        .WithMany()
                        .HasForeignKey("RoundRangeId")
                        .HasConstraintName("fk_end_roundrange");

                    b.HasOne("ArcheryWebsite.Models.Score", "Score")
                        .WithMany("Ends")
                        .HasForeignKey("ScoreId")
                        .IsRequired()
                        .HasConstraintName("end_ibfk_1");

                    b.Navigation("Range");

                    b.Navigation("RoundRange");

                    b.Navigation("Score");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.RoundEquivalence", b =>
                {
                    b.HasOne("Round", "EquivalentRound")
                        .WithMany("EquivalentRoundTargets")
                        .HasForeignKey("EquivalentRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Round", "Round")
                        .WithMany("EquivalentRoundDefinitions")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EquivalentRound");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Roundrange", b =>
                {
                    b.HasOne("ArcheryWebsite.Models.Range", "Range")
                        .WithMany("Roundranges")
                        .HasForeignKey("RangeId")
                        .IsRequired()
                        .HasConstraintName("roundrange_ibfk_2");

                    b.HasOne("Round", "Round")
                        .WithMany("Roundranges")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("roundrange_ibfk_1");

                    b.Navigation("Range");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Score", b =>
                {
                    b.HasOne("ArcheryWebsite.Models.Archer", "Archer")
                        .WithMany("Scores")
                        .HasForeignKey("ArcherId")
                        .IsRequired()
                        .HasConstraintName("score_ibfk_1");

                    b.HasOne("ArcheryWebsite.Models.Competition", "Comp")
                        .WithMany("Scores")
                        .HasForeignKey("CompId")
                        .HasConstraintName("score_ibfk_3");

                    b.HasOne("Round", "Round")
                        .WithMany("Scores")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("score_ibfk_2");

                    b.Navigation("Archer");

                    b.Navigation("Comp");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Stagingscore", b =>
                {
                    b.HasOne("ArcheryWebsite.Models.Archer", "Archer")
                        .WithMany("Stagingscores")
                        .HasForeignKey("ArcherId")
                        .IsRequired()
                        .HasConstraintName("stagingscore_ibfk_1");

                    b.HasOne("ArcheryWebsite.Models.Equipment", "Equipment")
                        .WithMany("Stagingscores")
                        .HasForeignKey("EquipmentId")
                        .IsRequired()
                        .HasConstraintName("stagingscore_ibfk_3");

                    b.HasOne("Round", "Round")
                        .WithMany("Stagingscores")
                        .HasForeignKey("RoundId")
                        .IsRequired()
                        .HasConstraintName("stagingscore_ibfk_2");

                    b.Navigation("Archer");

                    b.Navigation("Equipment");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Archer", b =>
                {
                    b.Navigation("Scores");

                    b.Navigation("Stagingscores");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Competition", b =>
                {
                    b.Navigation("Scores");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.End", b =>
                {
                    b.Navigation("Arrows");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Equipment", b =>
                {
                    b.Navigation("Stagingscores");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Range", b =>
                {
                    b.Navigation("Ends");

                    b.Navigation("Roundranges");
                });

            modelBuilder.Entity("ArcheryWebsite.Models.Score", b =>
                {
                    b.Navigation("Ends");
                });

            modelBuilder.Entity("Round", b =>
                {
                    b.Navigation("EquivalentRoundDefinitions");

                    b.Navigation("EquivalentRoundTargets");

                    b.Navigation("Roundranges");

                    b.Navigation("Scores");

                    b.Navigation("Stagingscores");
                });
#pragma warning restore 612, 618
        }
    }
}
